name: build-wheel

on:
  push:
    branches: [ "dist" ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install Build Tools
        run: python -m pip install wheel setuptools
        
      - name: Build wheels
        run: python setup.py bdist_wheel

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
